In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("../../datasets/play_tennis.csv")

In [3]:
data

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [4]:
#problem1
#Outlook=sunny temp=hot humidity=high wind=weak predict if play or not

In [5]:
#solution
#P(Yes/Sunny,hot,high,weak)=p(sunny/yes)*P(Hot/yes)*p(high/yes)*p(weak/yes)
#P(no/Sunny,hot,high,weak)=p(sunny/no)*P(Hot/no)*p(high/no)*p(weak/no)

In [6]:
#problem2
#outlook=overcast,temp=cold,humidity=lowmwind=weak
#play or no

In [8]:
#soln
# P(yes/overcast,cold,low,weak)=p(overcast/yes)*P(cold/yes)*p(low/yes)*p(weak/yes)
# P(no/overcast,cold,low,weak)=p(overcast/no)*P(cold/no)*p(low/no)*p(weak/no)

In [9]:
#training

#lookup table

#testing

In [10]:
#P(Yes)
#P(No)

In [13]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [15]:
py=9/14
pn=5/14

In [16]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [17]:
#Outlook
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [18]:
Pon=0
Prn=2/5
Psn=3/5
Poy=4/9
Pry=3/9
Psy=2/9

In [19]:
#temp
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [20]:
pCoolNo=1/5
pHotNo=2/5
pMildNo=2/5
pCoolyes=3/9
pHotyes=2/9
pMildYes=4/9

In [21]:
#Humidity
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [22]:
pHighno=4/5
pNormalno=1/5
pHighyes=3/9
pNormalyes=6/9

In [23]:
#wind
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [24]:
pStrongno=3/5
pWeakno=2/5
pStrongyes=3/9
pWeakyes=6/9

In [25]:
#ans to problem1

In [29]:
Pyes=py*Psy*pHotyes*pHighyes*pWeakyes

In [30]:
print(Pyes)

0.007054673721340388

In [32]:
Pno=pn*Psn*pHotNo*pHighno*pWeakno

In [33]:
print(Pno)

0.02742857142857143

In [ ]:
#No play according to Naive Bayes